[package]
name = "native"
version = "0.1.0"
authors = ["Joel Shepherd <github.com/joelshepherd>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13"
orion = "0.15"
